In [2]:
import numpy as np
import pandas as pd
from scipy import misc
import matplotlib.pyplot as plt
import pickle
%matplotlib inline

In [3]:
import pandas
df = pandas.read_excel(r'C:\Users\abdalah\Face Recognition\FaceNet\Data.xlsx')
coords = df.values

In [4]:
len(df.index)

8

In [5]:
len(df.columns)

450

In [6]:
df.head(10)

,"""1""","""2""","""3""","""4""","""5""","""6""","""7""","""8""",Unnamed: 8,Unnamed: 9,...,Unnamed: 440,Unnamed: 441,Unnamed: 442,Unnamed: 443,Unnamed: 444,Unnamed: 445,Unnamed: 446,Unnamed: 447,Unnamed: 448,Unnamed: 449
0,433.002547,189.175948,354.482117,172.645331,414.405603,424.737238,284.226995,371.012733,191.242275,201.573911,...,253.647619,257.347348,252.414376,369.572453,283.245449,433.701085,410.269470,152.521700,261.047077,259.813834
1,526.895473,522.762818,508.298529,539.293435,514.497510,518.630164,510.364856,520.696491,533.094454,512.431183,...,507.384539,507.384539,509.851025,509.851025,513.550753,528.349668,519.716968,522.183454,509.851025,518.483725
2,435.068874,191.242275,350.349462,174.711658,418.538257,424.737238,286.293322,371.012733,195.374929,197.441256,...,252.414376,254.880862,253.647619,365.872725,278.312478,433.701085,405.336498,143.889000,252.414376,261.047077
3,41.308602,61.971873,49.573911,115.696378,70.237182,51.640238,51.640238,92.966780,68.170855,61.971873,...,38.752230,42.451959,37.518988,43.685202,31.352773,39.985473,39.985473,36.285745,36.285745,44.918445
4,780.145501,534.252575,714.023033,505.323995,749.150594,771.880192,608.640351,691.293435,544.584211,532.186248,...,618.687522,634.719680,631.019952,718.580199,648.285352,811.073417,783.942073,522.494575,635.952923,649.518595
5,37.175948,59.905546,47.507583,109.497397,66.104527,49.573911,53.706565,86.767799,66.104527,61.971873,...,41.218716,42.451959,35.052502,46.151688,28.886287,37.518988,38.752230,36.285745,35.052502,46.151688
6,784.278155,534.252575,711.956706,505.323995,753.283248,773.946520,612.773005,693.359762,546.650538,534.252575,...,624.853737,639.652652,640.885895,723.513170,650.751838,814.773146,788.875045,543.459705,648.285352,645.818867
7,533.094454,524.829145,508.298529,539.293435,518.630164,522.762818,510.364856,518.630164,531.028127,514.497510,...,511.084267,509.851025,511.084267,508.617782,514.783996,528.349668,522.183454,533.282640,496.285352,517.250482

In [7]:
df.index[7]

7

In [8]:
from numpy import savez_compressed
from numpy import *
import imageio
for iFace in range(450):
    print(iFace)
    im =  imageio.imread(r'C:\Users\abdalah\Face Recognition\FaceNet\Caltech\image_%04d.jpg'%(iFace+1))
    coord = coords[:,iFace]

   # x = [int(min(coord[1],coord[3])),int(max(coord[5],coord[7]))]
   # y = [int(min(coord[2],coord[4])),int(max(coord[6],coord[8]))]
    
    x = [int(min(coord[0],coord[2])),int(max(coord[4],coord[6]))]
    y = [int(min(coord[1],coord[3])),int(max(coord[5],coord[7]))]
    dW = -10
    
    x[0] = max(0,x[0]-dW)
    x[1] = min(im.shape[1],x[1]+dW)
    y[0] = max(0,y[0]-dW)
    y[1] = min(im.shape[0],y[1]+dW)
    
#     width = x[1]-x[0]+50
#     height = y[1]-y[0]+50
#     L = max(width, height)
    
#     xmid = (x[1]+x[0])//2
#     xl = max(0,xmid -L//2)
#     xr = min(im.shape[1]-1,xl + L)
#     x = [xl,xr]
    
#     ymid = (y[1]+y[0])//2
#     yt = max(0,ymid -L//2)
#     yb = min(im.shape[0]-1,yt + L)
#     y = [yt,yb]
        
    face = im[y[0]:y[1],x[0]:x[1]]
    imageio.imsave(r'C:\Users\abdalah\Face Recognition\FaceNet\Caltech\Processed\cf%04d.png' % iFace, face)
#[x_bot_left y_bot_left x_top_left y_top_left x_top_right y_top_right x_bot_right y_bot_right]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449

In [9]:

idx_first = [0,21,41,46,68,89,112,132,137,158,165,170,175,195,216,241,263,268,287,307,336,356,376,398,399,400,401,402,403,408,428]

In [10]:
Labels = []
for i,idx in enumerate(idx_first):
    if i+1==len(idx_first):
        j = 449
    else:
        j = idx_first[i+1]-1
    nFace = j-idx+1
    for k in range(nFace):
        Labels.append(i)

In [11]:
len(Labels)

450

In [12]:
np.save(r'C:\Users\abdalah\Face Recognition\FaceNet\Caltech\Processed\Labels.xlsx',Labels)